# Generated by Django 5.2.14 on 2026-05-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BollingerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('stocks', models.JSONField(default=list, help_text='JSON list of NSE symbols — e.g. ["MSUMI"]')),
                ('period', models.IntegerField(default=20, help_text='Lookback period for the simple moving average and standard deviation.', verbose_name='SMA Period')),
                ('std_dev', models.FloatField(default=2.0, help_text='Band width = SMA ± (std_dev × StdDev). Standard value is 2.0.', verbose_name='Std Dev Multiplier')),
                ('candle_interval', models.CharField(choices=[('minute', '1 min'), ('3minute', '3 min'), ('5minute', '5 min'), ('10minute', '10 min'), ('15minute', '15 min'), ('30minute', '30 min'), ('60minute', '60 min')], default='5minute', max_length=20)),
                ('quantity_per_stock', models.IntegerField(default=1)),
                ('check_interval_minutes', models.IntegerField(default=5, verbose_name='Check Every (minutes)')),
                ('allow_short', models.BooleanField(default=False, help_text='If enabled, places a SELL order when price crosses back below the upper band.', verbose_name='Allow Short Selling')),
            ],
            options={
                'verbose_name': 'Bollinger Band Strategy',
                'verbose_name_plural': 'Bollinger Band Strategy',
            },
        ),
        migrations.CreateModel(
            name='FixedBuyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], default='MARKET', max_length=10)),
                ('execute_at', models.CharField(default='09:21', help_text='Time to place the fixed buy orders. Typically 1–2 minutes after market open.', max_length=5, verbose_name='Execute At (HH:MM IST)')),
            ],
            options={
                'verbose_name': 'Fixed Buy Strategy',
                'verbose_name_plural': 'Fixed Buy Strategy',
            },
        ),
        migrations.CreateModel(
            name='MACrossoverConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('stocks', models.JSONField(default=list, help_text='JSON list of NSE symbols — e.g. ["MSUMI", "RELIANCE"]')),
                ('fast_period', models.IntegerField(default=9, help_text='Number of candles for the fast EMA (typically 9).', verbose_name='Fast EMA Period')),
                ('slow_period', models.IntegerField(default=21, help_text='Number of candles for the slow EMA (typically 21).', verbose_name='Slow EMA Period')),
                ('candle_interval', models.CharField(choices=[('minute', '1 min'), ('3minute', '3 min'), ('5minute', '5 min'), ('10minute', '10 min'), ('15minute', '15 min'), ('30minute', '30 min'), ('60minute', '60 min')], default='5minute', max_length=20)),
                ('quantity_per_stock', models.IntegerField(default=1)),
                ('check_interval_minutes', models.IntegerField(default=5, verbose_name='Check Every (minutes)')),
            ],
            options={
                'verbose_name': 'MA Crossover Strategy',
                'verbose_name_plural': 'MA Crossover Strategy',
            },
        ),
        migrations.CreateModel(
            name='OpenRangeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('stocks', models.JSONField(default=list, help_text='JSON list of NSE symbols — e.g. ["MSUMI"]')),
                ('opening_range_minutes', models.IntegerField(default=15, help_text='High/low of the first N minutes forms the trading range. Default = 15 (9:15–9:30).', verbose_name='Opening Range (minutes)')),
                ('quantity_per_stock', models.IntegerField(default=1)),
                ('check_interval_minutes', models.IntegerField(default=1, verbose_name='Check Every (minutes)')),
                ('allow_short', models.BooleanField(default=False, help_text='If enabled, places a SELL order when price breaks below the range low.', verbose_name='Allow Short Selling')),
            ],
            options={
                'verbose_name': 'Open Range Breakout Strategy',
                'verbose_name_plural': 'Open Range Breakout Strategy',
            },
        ),
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_loss_pct', models.FloatField(default=1.5, help_text='Stop loss as % below (BUY) or above (SELL) entry price.', verbose_name='Stop Loss %')),
                ('target_pct', models.FloatField(default=3.0, help_text='Profit target as % above (BUY) or below (SELL) entry price.', verbose_name='Target Profit %')),
                ('max_daily_loss', models.FloatField(default=5000, help_text='Halt all new trades for the day once cumulative loss exceeds this.', verbose_name='Max Daily Loss (₹)')),
                ('max_open_positions', models.IntegerField(default=5, help_text='Maximum number of concurrent open MIS positions.', verbose_name='Max Open Positions')),
                ('auto_squareoff_time', models.CharField(default='15:15', help_text='All open positions will be squared off at this time daily.', max_length=5, verbose_name='Auto Square-off Time (HH:MM IST)')),
            ],
            options={
                'verbose_name': 'Risk Configuration',
                'verbose_name_plural': 'Risk Configuration',
            },
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.CharField(blank=True, max_length=30)),
                ('symbol', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(max_length=4)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='MARKET', max_length=10)),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('tag', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='PLACED', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trade Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ZerodhaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, verbose_name='User ID')),
                ('password', models.CharField(blank=True, help_text='Stored as plaintext in SQLite. Keep db.sqlite3 out of version control.', max_length=255, verbose_name='Password')),
                ('totp_secret', models.CharField(blank=True, help_text='Base-32 TOTP setup key from Zerodha 2FA setup. Leave blank to be prompted for the 6-digit code when the bot starts.', max_length=100, verbose_name='TOTP Secret (optional)')),
            ],
            options={
                'verbose_name': 'Zerodha Credentials',
                'verbose_name_plural': 'Zerodha Credentials',
            },
        ),
        migrations.CreateModel(
            name='FixedBuyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='NSE trading symbol, e.g. MSUMI', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.fixedbuyconfig')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('config', 'symbol')},
            },
        ),
    ]
