# Generated by Django 5.2.14 on 2026-05-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='openrangeconfig',
            name='max_entries_per_day',
            field=models.IntegerField(default=1, help_text="Maximum number of entry attempts per day. Set to 1 for the original one-trade-per-day behaviour. Increase when 'Trade Until Profit' is enabled (e.g. 5). 0 = unlimited (not recommended).", verbose_name='Max Entries Per Day'),
        ),
        migrations.AddField(
            model_name='openrangeconfig',
            name='stop_on_profit',
            field=models.BooleanField(default=False, help_text='Keep re-entering after a stop-loss until a trade closes profitably. Once a profitable trade closes, no more entries for the day.', verbose_name='Trade Until Profit'),
        ),
    ]
