# Generated by Django 5.2.14 on 2026-05-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_openrangeconfig_max_entries_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollingerconfig',
            name='max_entries_per_day',
            field=models.IntegerField(default=1, help_text="Max entry attempts per day. Set to 1 for original one-trade-per-day behaviour. Increase when 'Trade Until Profit' is enabled (e.g. 5). 0 = unlimited (not recommended).", verbose_name='Max Entries Per Day'),
        ),
        migrations.AddField(
            model_name='bollingerconfig',
            name='stop_on_profit',
            field=models.BooleanField(default=False, help_text='Keep re-entering after a stop-loss until a trade closes profitably. Once a profitable trade closes, no more entries for the day.', verbose_name='Trade Until Profit'),
        ),
        migrations.AddField(
            model_name='macrossoverconfig',
            name='max_entries_per_day',
            field=models.IntegerField(default=0, help_text='Max entry attempts per day. 0 = unlimited (original behaviour).', verbose_name='Max Entries Per Day'),
        ),
        migrations.AddField(
            model_name='macrossoverconfig',
            name='stop_on_profit',
            field=models.BooleanField(default=False, help_text='Wait for each position to close before looking for the next crossover. Stop trading for the day once a trade closes profitably.', verbose_name='Trade Until Profit'),
        ),
    ]
